#!/bin/bash
DOCKER_REGISTRY=docker.io
DOCKER_PROJECT_ID=djkormo

echo "DOCKER_REGISTRY: $DOCKER_REGISTRY"
echo "DOCKER_PROJECT_ID: $DOCKER_PROJECT_ID"


# logic 
SERVICE_NAME=np-logic
DOCKER_IMAGE_NAME=$DOCKER_PROJECT_ID/$SERVICE_NAME
DOCKER_IMAGE_REPO_NAME=$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME



echo "SERVICE_NAME: $SERVICE_NAME"
echo "DOCKER_IMAGE_NAME: $DOCKER_IMAGE_NAME"
echo "DOCKER_IMAGE_REPO_NAME: $DOCKER_IMAGE_REPO_NAME"


echo "..... Building $SERVICE_NAME"

#  build 

cd np-logic

docker build -t $SERVICE_NAME . -f Dockerfile

# tag

docker tag $SERVICE_NAME $DOCKER_IMAGE_NAME 


#push

docker push  $DOCKER_IMAGE_NAME

cd ..


# Webapp 

SERVICE_NAME=np-webapp
DOCKER_IMAGE_NAME=$DOCKER_PROJECT_ID/$SERVICE_NAME
DOCKER_IMAGE_REPO_NAME=$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME

echo "SERVICE_NAME: $SERVICE_NAME"
echo "DOCKER_IMAGE_NAME: $DOCKER_IMAGE_NAME"
echo "DOCKER_IMAGE_REPO_NAME: $DOCKER_IMAGE_REPO_NAME"

#  build 

echo "..... Building $SERVICE_NAME"

cd np-webapp

docker build -t $SERVICE_NAME . -f Dockerfile

# tag

docker tag $SERVICE_NAME $DOCKER_IMAGE_NAME 


#push

docker push  $DOCKER_IMAGE_NAME

cd ..



# frontend 
SERVICE_NAME=np-frontend
DOCKER_IMAGE_NAME=$DOCKER_PROJECT_ID/$SERVICE_NAME
DOCKER_IMAGE_REPO_NAME=$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME


echo "SERVICE_NAME: $SERVICE_NAME"
echo "DOCKER_IMAGE_NAME: $DOCKER_IMAGE_NAME"
echo "DOCKER_IMAGE_REPO_NAME: $DOCKER_IMAGE_REPO_NAME"

#  build 

echo "..... Building $SERVICE_NAME"

cd np-frontend

docker build -t $SERVICE_NAME . -f Dockerfile

# tag

docker tag $SERVICE_NAME $DOCKER_IMAGE_NAME 


#push

docker push  $DOCKER_IMAGE_NAME


cd ..



