FROM alpine:3.8

RUN apk --update add \
    curl git php-apache2 php-cli php-json php-mbstring php-phar php-openssl openrc && \
    rm -f /var/cache/apk/* && \
    curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin --filename=composer && \
    mkdir -p /var/www/html/ && chown -R apache:apache /var/www/html


RUN mkdir /run/apache2

COPY src/ /var/www/html/
COPY etc/apache2/httpd.conf /etc/apache2/httpd.conf
COPY etc/apache2/sites/ /etc/apache2/sites/
COPY etc/php/php.ini /etc/php7/php.ini

# cloning chess-ai from github
RUN git clone https://github.com/djkormo/simple-chess-ai

COPY index-blue.html simple-chess-ai/index.html

RUN cd simple-chess-ai && cp -R . /var/www/html && cd .. && rm -r simple-chess-ai/
RUN chown -R apache:apache /var/www/html

EXPOSE 80/tcp

ENTRYPOINT ["httpd"]
CMD ["-D","FOREGROUND"]







